# Mapping
resolution: 0.2
map_frame: "map"
fixed_frame: "odom"
robot_frame: "base_footprint"
offline_octomap_path: ""
# offline_octomap_path: "/home/sasm/pepper_nav_ws/src/pepper_pipeline/map/offline_map_2.bt"
visualize_free_space: True
mapping_max_range: 8
odometry_topic: "/pepper/odom_groundtruth"

rviz_timer: 1 # 0.0 if no visualization

point_cloud_topics: ["/pepper/camera/depth/points"]
point_cloud_frames: ["/CameraDepth_optical_frame"]

# social agents config
social_agents_topic: "/pedsim_simulator/simulated_agents"
social_agent_radius: 0.4

social_relevance_validity_checking: True
robot_distance_view_max: 8
robot_distance_view_min: 2
robot_angle_view: 2
robot_velocity_threshold: 0.35

social_heatmap_decay_factor: 0.2
